### ISSUE TITLE
Cannot overwrite prior netCDF encoding

### ISSUE THREAD

**Issue by jmcvey3** [tsdat/tsdat#103]
**Describe the bug**
netCDF files imported into tsdat already have encoding variables set. This error appears to be that the _FillValue is already set to nan, and xarray won't overwrite it with tsdat's -9999.

**To Reproduce**
Minimal set of steps to reproduce the behavior:
```
Use tsdat's native netCDF file reader to load a netcdf file
```

Please include the full traceback message (if applicable):
```
ERROR:utils.registry:Pipeline 'Turbulence' failed to process input: ['C:\\Users\\mcve343\\MRE_Resource_Ex\\pipelines\\turbulence\\data\\THEOM.vector_nospec.nc']
Traceback (most recent call last):
  File "c:\Users\mcve343\MRE_Resource_Ex\utils\registry.py", line 68, in dispatch
    pipeline.run(inputs)
  File "C:\Users\mcve343\Anaconda3\lib\site-packages\tsdat\pipeline\pipelines.py", line 28, in run
    dataset = decode_cf(dataset)
  File "C:\Users\mcve343\Anaconda3\lib\site-packages\tsdat\utils.py", line 97, in decode_cf
    ds: xr.Dataset = xr.decode_cf(dataset)  # type: ignore
  File "C:\Users\mcve343\Anaconda3\lib\site-packages\xarray\conventions.py", line 646, in decode_cf
    vars, attrs, coord_names = decode_cf_variables(
  File "C:\Users\mcve343\Anaconda3\lib\site-packages\xarray\conventions.py", line 512, in decode_cf_variables
    new_vars[k] = decode_cf_variable(
  File "C:\Users\mcve343\Anaconda3\lib\site-packages\xarray\conventions.py", line 355, in decode_cf_variable
    var = coder.decode(var, name=name)
  File "C:\Users\mcve343\Anaconda3\lib\site-packages\xarray\coding\variables.py", line 182, in decode
    raw_fill_values = [
  File "C:\Users\mcve343\Anaconda3\lib\site-packages\xarray\coding\variables.py", line 183, in <listcomp>
    pop_to(attrs, encoding, attr, name=name)
  File "C:\Users\mcve343\Anaconda3\lib\site-packages\xarray\coding\variables.py", line 129, in pop_to
    safe_setitem(dest, key, value, name=name)
  File "C:\Users\mcve343\Anaconda3\lib\site-packages\xarray\coding\variables.py", line 112, in safe_setitem
    raise ValueError(
ValueError: failed to prevent overwriting existing key _FillValue in attrs on variable 'battery_voltage'. This is probably an encoding field used by xarray to describe how a variable is serialized. To proceed, remove this key from the variable's attributes manually.
INFO:utils.registry:Processing completed with 0 successes, 1 failures, and 0 skipped.
```

**Expected behavior**

**Screenshots**
```
dataset.battery_voltage.encoding
{'zlib': True, 'shuffle': True, 'complevel': 1, 'fletcher32': False, 'contiguous': False, 'chunksizes': (4340,), 'source': 'C:\\Users\\mcve343\\MRE..._nospec.nc', 'original_shape': (4340,), 'dtype': dtype('float32'), '_FillValue': nan}
special variables
function variables
'zlib': True
'shuffle': True
'complevel': 1
'fletcher32': False
'contiguous': False
'chunksizes': (4340,)
'source': 'C:\\Users\\mcve343\\MRE_Resource_Ex\\pipelines\\turbulence\\data\\THEOM.vector_nospec.nc'
'original_shape': (4340,)
'dtype': dtype('float32')
'_FillValue': nan
len(): 10
```

**Environment** 

- OS: (Windows 10, WSL)
- `tsdat`: v0.4.2

**Comment by jmcvey3** [comment]
Closed with 2a8e34df030ff6f6b7319dbcf5e8d6b07c6c3e82
