### ISSUE TITLE
[BUG] Input FileHandlers are able override output FileHandlers 

### ISSUE THREAD

**Issue by maxwellevin** [tsdat/tsdat#16]
The `file_handlers` section of the storage config file has two sections: one for `input` and another for `output`. One would expect that FileHandlers registered in the `input` section are independent of those registered in the `output` section, but this is not the case. For a storage config file like below, tsdat tries to use the input FileHandler for writing to disk:

```
storage:
  # This section should not be modified unless there is a strong need. Please contact
  # the repository maintainers if you feel you need to use different settings here –
  # there may be another way to accomplish what you need.
  classname: ${STORAGE_CLASSNAME}
  parameters:
    retain_input_files: ${RETAIN_INPUT_FILES}
    root_dir: ${ROOT_DIR}
    bucket_name: ${STORAGE_BUCKET}

  file_handlers:
    input:
      scn:
        file_pattern: ".*"        # The regex pattern used to match to an input file.
                                  # Note this will only be applied to files already
                                  # matched by a mapping in mapping.py, so .* is fine
                                  # unless you need to use multiple handlers within
                                  # those matched files.
        classname: ingest.lidar_galion_g4000.pipeline.filehandler.ScnHandler

    # The output section should not be modified unless there is a strong need. Please
    # contact the repository maintainers if you feel you need to write to a different
    # format.
    output:
      netcdf:
        file_extension: ".nc"
        classname: tsdat.io.filehandlers.NetCdfHandler
```

See the error message below:
```
Traceback (most recent call last):
  File "/Users/levi260/github/forked/dzalkind/ingest-awaken/ingest/lidar_galion_g4000/runner.py", line 11, in <module>
    pipeline.run(
  File "/Users/levi260/github/forked/dzalkind/ingest-awaken/utils/pipeline.py", line 46, in run
    dataset = self.store_and_reopen_dataset(dataset)
  File "/Users/levi260/anaconda3/envs/galion/lib/python3.8/site-packages/tsdat/pipeline/pipeline.py", line 375, in store_and_reopen_dataset
    saved_paths = self.storage.save(dataset)
  File "/Users/levi260/anaconda3/envs/galion/lib/python3.8/site-packages/tsdat/io/storage.py", line 224, in save
    FileHandler.write(dataset, tmp_path)
  File "/Users/levi260/anaconda3/envs/galion/lib/python3.8/site-packages/tsdat/io/filehandlers/file_handlers.py", line 103, in write
    handler.write(ds, filename, config, **kwargs)
  File "/Users/levi260/github/forked/dzalkind/ingest-awaken/ingest/lidar_galion_g4000/pipeline/filehandler.py", line 27, in write
    raise NotImplementedError(
NotImplementedError: Error: this file format should not be used to write to.
```

**Comment by maxwellevin** [comment]
This has to do with the `FileHandler` class in `tsdat.io.filehandlers.file_handlers.py`; there is a central dictionary named `FILEHANDLERS` which makes no distinction between those registered for input/reading and those registered for output/writing.
